FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o producer ./cmd/producer

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/producer /app/producer
EXPOSE 2113
ENTRYPOINT ["/app/producer"]
