{
 "title": "Planet Scale Event Platform",
 "tags": [
  "kafka",
  "golang",
  "java"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Java Published Events / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(events_published_total[1m])"
    }
   ]
  },
  {
   "title": "Go Consumer Processed / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(consumer_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Go Consumer Failed / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(consumer_failed_total[1m])"
    }
   ]
  },
  {
   "title": "Processing Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(consumer_processing_seconds_bucket[1m])) by (le))"
    }
   ]
  }
 ]
}